
import type { PdfSelection } from '../pdf/pdf-types'
import type { PromptTransition } from '../prompts/prompt-types'

export type StableId = string
export type MessageRole = 'user' | 'assistant'

/** Frozen metadata for a Quick Follow-up user interaction. */
export type QuickFollowUpMetadata = {
  promptId?: StableId
  labelSnapshot: string
  promptSnapshot: string
}

/** Whether accepted-send should consume the current composer draft. */
export type DraftDisposition = 'clear' | 'preserve'

/** Pre-multi-range selection shape written by Stage 4-8 attachments in existing user data. */
export type PdfSelectionV1 = {
  kind: 'outline' | 'manual'
  title?: string
  startPage: number
  endPage: number
}

/** Provenance of an attachment generated by the app from a PDF page (not user-picked). */
export type PdfAttachmentSource = {
  type: 'pdf-page'
  /** One user-performed PDF context selection = one group. Never auto-merged by fileName. */
  groupId: StableId
  /** Optional reference to the persistent local LearningDocument this page came from.
   * Legacy Stage 4-9.3 attachments have no documentId and keep working as-is. */
  documentId?: string
  fileName: string
  pageNumber: number
  /** Accepted in BOTH shapes so pre-Stage-9.1 attachments keep loading/displaying. */
  selection: PdfSelection | PdfSelectionV1
}

/** The document/page provenance carried by a user message that included PDF pages. */
export type PdfContext = {
  documentId: string
  pageNumbers: number[]
  createdAt: number
}

/** Canonical attachment metadata. The binary blob lives in IndexedDB 'attachments' keyed by id. No base64/objectURL here.
 * source is OPTIONAL: ordinary user-uploaded images and all pre-Stage-5 attachments omit it. */
export type Attachment = { id: StableId; name: string; mimeType: string; size: number; createdAt: number; updatedAt: number; source?: PdfAttachmentSource }
/** Message holds only stable attachment id references, never objectURL/base64. */
export type Message = {
  id: StableId
  role: MessageRole
  content: string
  images: StableId[]
  createdAt: number
  updatedAt: number
  /** Canonical v1.3.1 provenance shape. New messages write this field only. */
  pdfContexts?: PdfContext[]
  /** Legacy v1.3.0 compatibility field. Read and normalized, never written for new messages. */
  pdfContext?: PdfContext
  /** v2: snapshot metadata for a real Quick Follow-up user interaction. */
  quickFollowUp?: QuickFollowUpMetadata
}

/** Read provenance from both the canonical and v1.3.0 legacy message shapes. */
export function pdfContextsOf(message: Pick<Message, 'pdfContexts' | 'pdfContext'>): PdfContext[] {
  if (Array.isArray(message.pdfContexts) && message.pdfContexts.length > 0) return message.pdfContexts
  return message.pdfContext ? [message.pdfContext] : []
}

/** Normalize a persisted message to the canonical shape without mutating it. */
export function normalizeMessagePdfContexts(message: Message): Message {
  const contexts = pdfContextsOf(message)
  const { pdfContext: _legacy, ...withoutLegacy } = message
  return contexts.length > 0 ? { ...withoutLegacy, pdfContexts: contexts } : withoutLegacy
}

/** Normalize every message in a persisted conversation. */
export function normalizeConversationPdfContexts<T extends { messages: Message[] }>(conversation: T): T {
  return { ...conversation, messages: conversation.messages.map(normalizeMessagePdfContexts) }
}
export type Conversation = { id: StableId; title: string; createdAt: number; updatedAt: number; messages: Message[]; promptTransitions?: PromptTransition[] }
export const NEW_TITLE = '新会话'
export function newStableId(): StableId { return globalThis.crypto.randomUUID() }
