
export type StableId = string
export type MessageRole = 'user' | 'assistant'
/** Provenance of an attachment generated by the app from a PDF page (not user-picked). */
export type PdfAttachmentSource = {
  type: 'pdf-page'
  /** One user-performed PDF context selection = one group. Never auto-merged by fileName. */
  groupId: StableId
  fileName: string
  pageNumber: number
  selection: {
    kind: 'outline' | 'manual'
    title?: string
    startPage: number
    endPage: number
  }
}

/** Canonical attachment metadata. The binary blob lives in IndexedDB 'attachments' keyed by id. No base64/objectURL here.
 * source is OPTIONAL: ordinary user-uploaded images and all pre-Stage-5 attachments omit it. */
export type Attachment = { id: StableId; name: string; mimeType: string; size: number; createdAt: number; updatedAt: number; source?: PdfAttachmentSource }
/** Message holds only stable attachment id references, never objectURL/base64. */
export type Message = { id: StableId; role: MessageRole; content: string; images: StableId[]; createdAt: number; updatedAt: number }
export type Conversation = { id: StableId; title: string; createdAt: number; updatedAt: number; messages: Message[] }
export const NEW_TITLE = '新会话'
export function newStableId(): StableId { return globalThis.crypto.randomUUID() }